function getSpoilerUrl(cardName) {
    return "http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/" + cardName;
}

var enumValues = {
    factions: {
        anarch:   'Anarch',
        criminal: 'Criminal',
        hb:       'Haas-Bioroid',
        jinteki:  'Jinteki',
        nbn:      'NBN',
        shaper:   'Shaper',
        weyland:  'The Weyland Consortium',
    },
    sets: {
        core:    'Core',
    },
    sides: {
        corp:   'Corp',
        runner: 'Runner',
    },
    types: {
        agenda:    'Agenda',
        asset:     'Asset',
        event:     'Event',
        hardware:  'Hardware',
        ice:       'ICE',
        identity:  'Identity',
        operation: 'Operation',
        program:   'Program',
        resource:  'Resource',
        upgrade:   'Upgrade',
    },
};

var referenceCards = {
    noise: {
        baselink:       0,
        code:           "01001",
        faction:        enumValues.factions.anarch,
        influencelimit: 15,
        mindecksize:    45,
        maxperdeck:     1,
        number:         1,
        quantity:       1,
        set:            enumValues.sets.core,
        side:           enumValues.sides.runner,
        subtype:        "G-mod",
        title:          "Noise: Hacker Extraordinaire",
        type:           enumValues.types.identity,
        url:            getSpoilerUrl("noise-hacker-extraordinaire-core"),
    },
    dejavu: {
        code:        "01002",
        cost:        2,
        faction:     enumValues.factions.anarch,
        factioncost: 2,
        number:      2,
        maxperdeck:  3,
        quantity:    2,
        set:         enumValues.sets.core,
        side:        enumValues.sides.runner,
        subtype:     '',
        title:       "Déjà Vu",
        type:        enumValues.types.event,
        url:         getSpoilerUrl('deja-vu-core'),
    },
    cyberfeeder: {
        code:        "01005",
        cost:        2,
        faction:     enumValues.factions.anarch,
        factioncost: 1,
        number:      5,
        maxperdeck:  3,
        quantity:    3,
        set:         enumValues.sets.core,
        side:        enumValues.sides.runner,
        subtype:     "Chip",
        title:       "Cyberfeeder",
        type:        enumValues.types.hardware,
        uniqueness:  false,
        url:         getSpoilerUrl('cyberfeeder-core'),
    },
    corroder: {
        code:        "01007",
        cost:        2,
        faction:     enumValues.factions.anarch,
        factioncost: 2,
        memoryunits: 1,
        number:      7,
        maxperdeck:  3,
        quantity:    2,
        set:         enumValues.sets.core,
        side:        enumValues.sides.runner,
        strength:    2,
        subtype:     "Icebreaker - Fracter",
        title:       "Corroder",
        type:        enumValues.types.program,
        uniqueness:  false,
        url:         getSpoilerUrl('corroder-core'),
    },
    datasucker: {
        code:        "01008",
        cost:        1,
        faction:     enumValues.factions.anarch,
        factioncost: 1,
        maxperdeck:  3,
        memoryunits: 1,
        number:      8,
        quantity:    2,
        set:         enumValues.sets.core,
        side:        enumValues.sides.runner,
        subtype:     "Virus",
        title:       "Datasucker",
        type:        enumValues.types.program,
        uniqueness:  false,
        url:         getSpoilerUrl("datasucker-core"),
    },
    icecarver: {
        code:        "01015",
        cost:        3,
        faction:     enumValues.factions.anarch,
        factioncost: 3,
        number:      15,
        maxperdeck:  3,
        quantity:    1,
        set:         enumValues.sets.core,
        side:        enumValues.sides.runner,
        subtype:     "Virtual",
        title:       "Ice Carver",
        type:        enumValues.types.resource,
        uniqueness:  true,
        url:         getSpoilerUrl("ice-carver-core"),
    },
    hbetf: {
        code:           "01054",
        faction:        enumValues.factions.hb,
        influencelimit: 15,
        mindecksize:    45,
        number:         54,
        maxperdeck:     1,
        quantity:       1,
        set:            enumValues.sets.core,
        side:           enumValues.sides.corp,
        subtype:        "Megacorp",
        title:          "Haas-Bioroid: Engineering the Future",
        type:           enumValues.types.identity,
        url:            getSpoilerUrl('haas-bioroid-engineering-the-future-core'),
    },
    abt: {
        agendapoints: 2,
        code:         "01055",
        cost:         3,
        faction:      enumValues.factions.hb,
        factioncost:  null,
        number:       55,
        maxperdeck:   3,
        quantity:     3,
        set:          enumValues.sets.core,
        side:         enumValues.sides.corp,
        subtype:      "Research",
        title:        "Accelerated Beta Test",
        type:         enumValues.types.agenda,
        uniqueness:   false,
        url:          getSpoilerUrl('accelerated-beta-test-core'),
    },
    adonis: {
        code:        "01056",
        cost:        4,
        faction:     enumValues.factions.hb,
        factioncost: 2,
        number:      56,
        maxperdeck:  3,
        quantity:    3,
        set:         enumValues.sets.core,
        side:        enumValues.sides.corp,
        subtype:     "Advertisement",
        title:       "Adonis Campaign",
        trash:       3,
        type:        enumValues.types.asset,
        uniqueness:  false,
        url:         getSpoilerUrl('adonis-campaign-core'),
    },
    archivedmemories: {
        code:        "01058",
        cost:        0,
        faction:     enumValues.factions.hb,
        factioncost: 2,
        number:      58,
        maxperdeck:  3,
        quantity:    2,
        set:         enumValues.sets.core,
        side:        enumValues.sides.corp,
        subtype:     '',
        title:       "Archived Memories",
        type:        enumValues.types.operation,
        url:         getSpoilerUrl('archived-memories-core'),
    },
    heimdall1: {
        code:        "01061",
        cost:        8,
        faction:     enumValues.factions.hb,
        factioncost: 2,
        number:      61,
        maxperdeck:  3,
        quantity:    2,
        set:         enumValues.sets.core,
        side:        enumValues.sides.corp,
        subtype:     "Barrier - Bioroid - AP",
        title:       "Heimdall 1.0",
        type:        enumValues.types.ice,
        uniqueness:  false,
        url:         getSpoilerUrl('heimdall-1-0-core'),
    },
    troubleshooter: {
        code:        "01065",
        cost:        0,
        faction:     enumValues.factions.hb,
        factioncost: 1,
        number:      65,
        maxperdeck:  3,
        quantity:    1,
        set:         enumValues.sets.core,
        side:        enumValues.sides.corp,
        subtype:     "Connection",
        title:       "Corporate Troubleshooter",
        trash:       2,
        type:        enumValues.types.upgrade,
        uniqueness:  false,
        url:         getSpoilerUrl('corporate-troubleshooter-core'),
    },
};

module.exports = {
    referenceCards: referenceCards,
};
